import { createChat, getChatHistoryByUser } from "../models/chatModel.js";
import { createFeedback, getRecentFeedbackContext } from "../models/feedbackModel.js";
import { queryAIEngineWithContext } from "../services/aiEngineService.js";

const formatFeedbackContext = (rows) => {
  if (!rows.length) {
    return "No recent feedback available.";
  }

  return rows
    .map((row, index) => {
      const ratingText = Number(row.rating) >= 4 ? "positive" : Number(row.rating) <= 2 ? "negative" : "mixed";
      const commentText = row.comment ? row.comment.trim() : "No comment provided.";
      return `${index + 1}. ${ratingText} (${row.rating}/5): ${commentText}`;
    })
    .join("\n");
};

export const createChatMessage = async (req, res, next) => {
  try {
    const { message, topK = 4 } = req.body;

    if (!message || !message.trim()) {
      return res.status(400).json({ message: "message is required" });
    }

    const queriedAt = new Date().toISOString();
    let feedbackContext = "No recent feedback available.";

    try {
      const recentFeedback = await getRecentFeedbackContext(10);
      feedbackContext = formatFeedbackContext(recentFeedback);
    } catch {
      feedbackContext = "No recent feedback available.";
    }

    let aiResult;
    try {
      aiResult = await queryAIEngineWithContext(message.trim(), topK, { feedbackContext });
    } catch (error) {
      return res.status(502).json({
        message: "AI engine unavailable",
        error: error.message,
      });
    }

    const aiResponse = aiResult.answer || "No response generated by AI engine.";

    const chat = await createChat({
      userId: req.user.id,
      userMessage: message.trim(),
      aiResponse,
    });

    return res.status(201).json({
      message: "Chat message stored",
      data: {
        id: chat.id,
        user_id: chat.user_id,
        user_message: chat.user_message,
        ai_response: aiResponse,
        created_at: chat.created_at,
        metadata: {
          queried_at: queriedAt,
          user_id: req.user.id,
          user_role: req.user.role,
          confidence_score: aiResult.confidence_score ?? 0,
          fallback: Boolean(aiResult.fallback),
          citations: aiResult.citations || [],
          source: aiResult.source || "documents",
          web_sources: aiResult.web_sources || [],
        },
      },
    });
  } catch (error) {
    return next(error);
  }
};

export const submitFeedback = async (req, res, next) => {
  try {
    const chatId = Number(req.params.chatId);
    const rating = Math.max(1, Math.min(5, Number(req.body.rating) || 0));
    const comment = typeof req.body.comment === "string" ? req.body.comment.trim() : "";

    if (!chatId) {
      return res.status(400).json({ message: "valid chat id is required" });
    }

    if (!rating) {
      return res.status(400).json({ message: "rating is required" });
    }

    const feedback = await createFeedback({
      chatId,
      userId: req.user.id,
      rating,
      comment,
    });

    return res.status(201).json({
      message: "Feedback recorded",
      data: feedback,
    });
  } catch (error) {
    return next(error);
  }
};

export const getChatHistory = async (req, res, next) => {
  try {
    const history = await getChatHistoryByUser(req.user.id, req.query.limit);
    return res.json({
      message: "Chat history fetched",
      data: history,
    });
  } catch (error) {
    return next(error);
  }
};